// Membuat custom exception dengan mewarisi (extends) class Exception.
// Berbeda dengan 'extends Throwable' di percobaan sebelumnya, ini adalah standar praktik terbaik di Java.
class MyException extends Exception {

    private String Teks;

    // Constructor custom exception untuk memproses pesan teks yang dikirim
    MyException(String s) {
        Teks = "Exception generated by: " + s;
        // Langsung mencetak pesan saat objek exception ini dibuat/di-instansiasi
        System.out.println(Teks);
    }
}

class Eksepsi {

    // 'throws Exception' pada deklarasi method memberi tahu compiler 
    // bahwa method ini berpotensi melempar checked exception, sehingga pemanggil method ini wajib menanganinya.
    static void tampil(String s) throws Exception {
        System.out.println("Tampil");
        
        // Memeriksa isi string. Jika inputnya adalah "amir", exception dipicu.
        if (s.equals("amir")) {
            // Melempar objek objek MyException secara manual
            throw new MyException(s);
        }
        
        // Baris ini HANYA dieksekusi jika kondisi IF di atas tidak terpenuhi (artinya tidak ada throw)
        System.out.println("OK!");
    }

    public static void main(String[] args) throws Exception {
        try {
            // Eksekusi 1: Mengirim "ali". Karena tidak sama dengan "amir", method berjalan normal sampai mencetak "OK!".
            tampil("ali");
            
            // Eksekusi 2: Mengirim "amir". Kondisi terpenuhi, MyException dilempar, dan alur try langsung BERHENTI di sini.
            tampil("amir");
            
        } catch (MyException ex) {
            // Menangkap error MyException secara spesifik. 
            // Mencetak objek 'ex' secara otomatis memanggil method toString() internal bawaan Java, menampilkan nama class exception-nya.
            System.out.println("Tangkap: " + ex);
        }
    }
}